services:
  cache:
    extends:
      file: docker-compose.base.yaml
      service: cache
      image: redis/redis-stack-server:latest
      env_file:
        - .env.prod
      # TODO: use redis.conf instead
  app:
    extends:
      file: docker-compose.yaml
      service: app
    env_file:
      - .env.prod
    depends_on:
      - cache
volumes:
  cache-vol:
    driver: local
