services:
  app:
    build: .
    ports:
      - 3001:3001
    environment:
      NODE_EXTRA_CA_CERTS: "/app/config/cert.pem"
      PORT: 3001
      ANNOUNCED_ADDRESS: 127.0.0.1
      # ANNOUNCED_ADDRESS: Elastic IP OR Public Static IP of server hosting this app
    volumes:
      - type: bind
        source: ./server.ts
        target: /app/server.ts
        read_only: true
