name: Lint code
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint:
    name: Lint frontend code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use node.js 22.13.1
        uses: actions/setup-node@v4
        with:
          node_version: "22.x"
      - run: npm ci
      - run: echo "Linting frontend" \
          && npm run lint \
          && echo "Linting signaling server" \
          && cd signaling \
          && npm run lint
